version: "3"

services:

  symfony_app:
    volumes:
      - "$FEATER__SOURCE_MOUNT__SYMFONY_EXAMPLE:/var/www/html"
    environment:
      FEATER__INSTANCE_HASH: "$FEATER__INSTANCE_HASH"

  symfony_db:
    volumes:
      - "test_db:/var/lib/mysql"

  symfony_elasticsearch:
    volumes:
      - "test_elasticsearch:/usr/share/elasticsearch/data"

volumes:
  test_db:
    external:
      name: "$FEATER__ASSET_VOLUME__TEST_DB"
  test_elasticsearch:
    external:
      name: "$FEATER__ASSET_VOLUME__TEST_ELASTICSEARCH"
