version: "3"

services:

  symfony_app:
    volumes:
      - "symfony_example:/var/www/html"
    environment:
      FEATER__INSTANCE_HASH: "$FEATER__INSTANCE_HASH"

  symfony_db:
    volumes:
      - "test_db:/var/lib/mysql"

volumes:
  test_db:
    external:
      name: "$FEATER__ASSET_VOLUME__TEST_DB"
  symfony_example:
    external:
      name: "$FEATER__SOURCE_VOLUME__SYMFONY_EXAMPLE"
